@startuml
title Future Network Layout with VLAN Segmentation

skinparam component {
    BackgroundColor Khaki
    BorderColor Black
    FontColor Black
}


rectangle "Router" as Router {
    [**ID: 01**\nSpeedport Smart 3] as Router_Device
}

[**ID: 28**\nSwitch (1 Gps, 5 Ports)\nTP-Link TL-SG1005D] as SWITCH_REPEATER

[**ID: 29**\nWLAN Access Point\nTP-Link TL-WA1201] as REPEATER

rectangle "Firewall                            " as FW_Domain {
	rectangle "**ID: 02                                **\nN100                                 " as FW #Khaki {
    		circle "WAN (ETH0)" as FW_ETH_WAN
    		circle "Office (ETH1)" as FW_ETH_Office
    		circle "Media (ETH2)" as FW_ETH_Media
    		circle "Central (ETH3)" as FW_ETH_Central
    		circle "Servers (ETH4)" as FW_ETH_Servers
    		circle "unused (ETH5)" as FW_ETH_free
	}
}

rectangle "Office Network" as Office {
  	
    [**ID: 03:**\nSwitch (1 Gbps, 8 Ports)\nTP-Link TL-SG108] as SWITCH_OFFICE 

    [**ID: 04:**\nMac Mini] as PC_Mac
    [**ID: 05:**\nZotac Nano AQ01] as PC_Zotac
    [**ID: 06:**\nMNBOXCONET (N305)] as PC_MNBOX

    rectangle "Docking Station" as Dock {
        [**ID: 07:**\nLatitude 5521 (Work)] as Dock_Latitude
        [**ID: 08:**\nDell G16 Laptop] as Dock_G16
    }

    rectangle "Loose Network Cable\n(used for temporary connections)" as LooseCable {
        [**ID: 09:**\nLenovo 430s Laptop] as Cable_Lenovo
        [**ID: 10:**\nSony Vaio Laptop] as Cable_Sony
    }
}

rectangle "Media Network" as Media {
	
    [**ID: 11:**\nSwitch (1 Gbps, 5 Ports)\nNetgear] as SWITCH_MEDIA

    [**ID: 12:**\nZotac Nano CI302\nMedia Player] as Media_Zotac
    [**ID: 13**\nHama\nInternet Radio] as Media_Radio
    [**ID: 14**\nSamsung\nSmart TV] as Media_TV
}

rectangle "Central Network" as Central {
	
    [**ID: 15:**\nSwitch (1 Gbps, 8 Ports)\nTP-Link TL-SG108] as SWITCH_CENTRAL

    [**ID: 16**\nHP Smart Tank Plus 5105\nPrinter] as Central_Printer
    [**ID: 17**\nQNAP 419 PII\nNAS] as Central_NAS
}

rectangle "Server Network (2.5Gbps)" as ServerNet {

    [**ID: 18:**\nSwitch (2.5 Gbps, 8 Ports)\nKeeplink] as SWITCH_SERVERS

    rectangle "Kubernetes Cluster" as K8s #Darkgrey {
	    rectangle "VLAN 40: Production Services" as VLAN40 #Coral {
		rectangle "Cluster Network (10Gbps)" as ClusterNet #White {
    			folder "Distributed File System (DFS)\ne.g. Longhorn or Ceph" as DFS
        		[**ID: 25**\nSwitch (10 Gbps, 8 Ports)\nSODOLA 8-Port 10G Web Managed Switch] as SWITCH_CLUSTER
        		[**ID: 19**\nMNBOXCONET N305\nKubernetes Node 1] as Cluster_Node_1
        		[**ID: 20**\nMNBOXCONET N305\nKubernetes Node 2] as Cluster_Node_2
        		[**ID: 21**\nMNBOXCONET N305\nKubernetes Node 3] as Cluster_Node_3
        		[**ID: 22**\nMNBOXCONET N305\nKubernetes Node 4] as Cluster_Node_4
        		[**ID: 26**\nMac Mini M4\nKubernetes Node 5] as Cluster_Node_5 #White
        		[**ID: 27**\nMac Mini M4\nKubernetes Node 6] as Cluster_Node_6 #White
		}
	        [**ID: 30**\nFujitsu Futuro 930\nWeb Server] as Web_Server #White
		folder "Local Storage\n(internal or\nUSB)" as local_storage
    	  }
     }

     rectangle "VLAN 60: Storage/Backup" as VLAN60 #CornflowerBlue {
        [***ID: 24**\nTerramaster F4-423\nNAS] as NAS_Storage
     }

     rectangle "VLAN 50: Maintenance and Diagnostics" as VLAN50 #DarkGreen {
        [**ID: 23**\nFujitsu Futuro 930\nMaintenance Server] as Maintenance_Server
    }
}

Router_Device -- SWITCH_REPEATER
SWITCH_REPEATER -- REPEATER
SWITCH_REPEATER -- FW_ETH_WAN

FW_ETH_WAN -[hidden]- FW_ETH_Office
FW_ETH_WAN -[hidden]- FW_ETH_Media
FW_ETH_WAN -[hidden]- FW_ETH_Central
FW_ETH_WAN -[hidden]- FW_ETH_Servers
FW_ETH_WAN -[hidden]- FW_ETH_free

FW_ETH_Office --- SWITCH_OFFICE
FW_ETH_Media --- SWITCH_MEDIA
FW_ETH_Central --- SWITCH_CENTRAL
FW_ETH_Servers --- SWITCH_SERVERS

SWITCH_OFFICE -- PC_Mac
SWITCH_OFFICE -- PC_Zotac
SWITCH_OFFICE -- PC_MNBOX
SWITCH_OFFICE -- Dock
SWITCH_OFFICE -- LooseCable : Optional connection

LooseCable .- Cable_Lenovo : Ad-hoc
LooseCable .- Cable_Sony : Ad-hoc

Dock -.- Dock_Latitude : Option 1
Dock -.- Dock_G16 : Option 2

SWITCH_MEDIA -- Media_Zotac
SWITCH_MEDIA -- Media_Radio
SWITCH_MEDIA -- Media_TV

SWITCH_CENTRAL -- Central_Printer
SWITCH_CENTRAL -- Central_NAS

SWITCH_SERVERS -[hidden]- VLAN40 : Production Services
SWITCH_SERVERS -[hidden]- VLAN50 : Maintenance and Diagnostics
SWITCH_SERVERS -[hidden]- VLAN60 : Storage/Backup

SWITCH_SERVERS -- SWITCH_CLUSTER
SWITCH_SERVERS -- Maintenance_Server 
SWITCH_SERVERS -- Web_Server 
SWITCH_SERVERS -- NAS_Storage 

Web_Server ... local_storage

SWITCH_CLUSTER -- Cluster_Node_1
SWITCH_CLUSTER -- Cluster_Node_2
SWITCH_CLUSTER -- Cluster_Node_3
SWITCH_CLUSTER -- Cluster_Node_4
SWITCH_CLUSTER -- Cluster_Node_5
SWITCH_CLUSTER -- Cluster_Node_6

SWITCH_CLUSTER ----- PC_MNBOX : direct cluster \n access 10 GBit/s

DFS ... Cluster_Node_1
DFS ... Cluster_Node_2
DFS ... Cluster_Node_3
DFS ... Cluster_Node_4
DFS ... Cluster_Node_5
DFS ... Cluster_Node_6
DFS ... NAS_Storage: backup




K8s ... NAS_Storage: provides storage, hosts docker registry


' note top of ServerNet : VLANs logically isolate server functions.
note top of FW_ETH_free : Might later be used to connect WLAN extenders

note top of SWITCH_REPEATER : WLAN Traffic is not routed via the firewall as it is handled by the router anyway

@enduml

