@startuml
title Details of the subnet "Office" with the docking station and cable connection for the Laptops - selected participants also interact with the subnet "Server"

[Firewall]

rectangle "Server Network" as SERVER_NETWORK {

	
}

rectangle "Office Network" as OFFICE_NETWORK {
    [**ID: 03:**\nSwitch (1 Gbps, 8 Ports)\nTP-Link TL-SG108] as SWITCH_OFFICE 
    [**ID: 05:**\nMini PC\nZotac Nano AQ01] as ZOTAC_AQ1

    rectangle "used interactively or as K8s nodes" as KUBERNETES #Darkgrey {
        [**ID: 04:**\nMini PC\nMac Mini (2020)] as MAC_MINI
 	rectangle "**ID: 06:**\nMini PC\nMNBOXCONET N305]" as MNBOXCONET_ALL #White  {
        	[**ID: 06:**\nMini PC\nMNBOXCONET\nPromaox] as MNBOXCONET_HOST
	        [**ID: 60:**\nVM (N305)\n] as MNBOXCONET_VM1
	        [**ID: 61:**\nVM (N305)\n] as MNBOXCONET_VM2
		
	}
    }

    rectangle "Loose Network Cable\n(used for temporary connections)" as LOOSE_NETWORK_CABLE {
        [**ID: 09:**\nLenovo 430s Laptop] as LENOVO
        [**ID: 10:**\nSony Vaio Laptop] as SONY_VAIO
    }

    rectangle "Docking Station" as DOCKING_STATION {
        [**ID: 07:**\nLatitude 5521 (Work)] as DELL_LATITUDE
        [**ID: 08:**\nDell G16 Laptop] as DELL_G16
    }
}

MNBOXCONET_VM1 -down- SERVER_NETWORK
MNBOXCONET_VM2 -down- SERVER_NETWORK

MNBOXCONET_VM1 -[hidden]- MNBOXCONET_HOST : 10 GBit/s
MNBOXCONET_VM2 -[hidden]- MNBOXCONET_HOST : 10 GBit/s

SERVER_NETWORK --- MNBOXCONET_HOST : 2.5 GBit/s Monitoring
SERVER_NETWORK --- MAC_MINI : 10 GBit/s

Firewall -- SWITCH_OFFICE

SWITCH_OFFICE -- MAC_MINI
SWITCH_OFFICE -- ZOTAC_AQ1
SWITCH_OFFICE -- MNBOXCONET_HOST
SWITCH_OFFICE -- DOCKING_STATION
SWITCH_OFFICE -- LOOSE_NETWORK_CABLE : Optional connection
' SWITCH_OFFICE -- MNBOXCONET_ALL

LOOSE_NETWORK_CABLE -.- LENOVO : Ad-hoc
LOOSE_NETWORK_CABLE -.- SONY_VAIO : Ad-hoc

DOCKING_STATION -.- DELL_LATITUDE : Option 1
DOCKING_STATION -.- DELL_G16 : Option 2

@enduml

