@startuml
title Details of the Subnet "Server" (2.5 gbps) with the Cluster

skinparam maxWidth 2000
skinparam maxHeight 900
scale 0.7

skinparam component {
    BackgroundColor Khaki
    BorderColor Black
    FontColor Black
}

[Firewall]

rectangle "Office Network" as OFFICE_NETWORK {
	rectangle "MNBOXCONET" as OFFICE_MNBOX_ALL #line.dashed {
        		[**ID: 06**\nMini PC\nMNBOXCONET\nPromox] as OFFICE_MNBOX_HOST
        		[**ID: 36**\nVM (N305)\nK8s Node 09] as CLUSTER_NODE_09
        		[**ID: 37**\nVM (N305)\nK8s Node 10] as CLUSTER_NODE_10
         }

        [**ID: 04**\nMini PC\nMac Mini (2020)\n8GB 2TB (extern)] as OFFICE_MAC
} 

rectangle "Server Network (2.5Gbps)" as SERVER_NETWORK {
    [**ID: 18:**\nSwitch (2.5 Gbps, 8 Ports)\nKeeplink] as SWITCH_SERVERS

     rectangle "VLAN 60: Storage/Backup" as VLAN60 #LightBlue {
        [***ID: 24**\nNAS (2.5 GBit/s, 4x8TB)\nTerramaster F4-423] as NAS_TERRAMASTER
        [***ID: 05**\nZotac Nano 520 (2.5 GBit/s)\nNAS Cache] as SERVER_NAS_CACHE
     }

     rectangle "VLAN 50: Maintenance and Diagnostics" as VLAN50 #PaleGreen {
        rectangle "**ID: 31**\nVM Host (Glovary N305)" as VM_HOST #LightGrey {
        	rectangle "**VM**\nNAS Buffer\nFast Backups\n **option if need arrises**" as VM_NAS #White {
		}	
        	rectangle "**VM**\n Glovary General Server\nshared with Host System" as VM_GENERAL #LightBlue {
		}
        	rectangle "**VM**\nGlovary Switch (VM)\nkeeps networking funct. separated\nindependend config and mgmt\nlimit access" as VM_SWITCH #LightGreen {
			circle "ETH_3" as E3
			circle "ETH_4" as E4
			circle "ETH_5" as E5
			circle "ETH_6" as E6
			
}
                
		circle "ETH_1: UPLINK" as E1
		circle "ETH_2" as E2	

                E1 -[hidden]- E2
                E1 -[hidden]- E3
                E1 -[hidden]- E4
                E1 -[hidden]- E5
                E1 -[hidden]- E6
 
	}


    }

    rectangle "VLAN 70: Cluster Host" as CLUSTER_HOST {
        [**ID: 38**\nMNBOXCONET N305\nPromox]	as CLUSTER_HOST_1
        [**ID: 39**\nMNBOXCONET N305\nPromox]	as CLUSTER_HOST_2
 '       [**ID: 40**\nMNBOXCONET N305\nPromox]	as CLUSTER_HOST_3
        [**ID: 40**\nMINDSFORUM MS-01\nPromox]	as CLUSTER_HOST_3 #White
        [**ID: 41**\nMINDSFORUM MS-01\nPromox]	as CLUSTER_HOST_4 #White
    }

    rectangle "Kubernetes Cluster" as K8s #Darkgrey {
	    rectangle "VLAN 40: Production Services" as VLAN40 #LightCoral {
		rectangle "Cluster Network (10Gbps)" as ClusterNet #White {
    			folder "Distributed File System (DFS)\ne.g. Longhorn or Ceph" as DFS
        		[**ID: 25**\nSwitch (10 Gbps, 12 Ports)\nBinardat 12-Port 10G Web Managed Switch] as SWITCH_CLUSTER
'        		[**ID: 49**\nSwitch 2 (10 Gbps, 8 Ports)\nSODOLA 8-Port 10G Web Managed Switch] as SWITCH_CLUSTER2 #White
        		[**ID: 19**\nVM (N305)\nK8s Node 01] as CLUSTER_NODE_01
        		[**ID: 20**\nVM (N305)\nK8s Node 02] as CLUSTER_NODE_02
        		[**ID: 21**\nVM (N305)\nK8s Node 03] as CLUSTER_NODE_03
        		[**ID: 22**\nVM (N305)\nK8s Node 04] as CLUSTER_NODE_04
         		[**ID: 32**\nVM (i9)\nK8s Node 05] as CLUSTER_NODE_05 #White
        		[**ID: 33**\nVM (i9)\nK8s Node 06] as CLUSTER_NODE_06 #White
        		[**ID: 34**\nVM (i9)\nK8s Node 07] as CLUSTER_NODE_07 #White
        		[**ID: 35**\nVM (i9)\nK8s Node 08] as CLUSTER_NODE_08 #White
		}
    	  }
     }
}
SWITCH_SERVERS -- E1 : 1 
SWITCH_SERVERS -- NAS_TERRAMASTER : 3
SWITCH_SERVERS -- SERVER_NAS_CACHE : 2
SWITCH_SERVERS --right-- OFFICE_MNBOX_HOST :6
E4 -- CLUSTER_HOST_1
E5 -- CLUSTER_HOST_2
E6 -- CLUSTER_HOST_3
E3 -- CLUSTER_HOST_4

SWITCH_SERVERS --- SWITCH_CLUSTER : 4 / uplink
SWITCH_SERVERS --- OFFICE_MAC : 5 
SWITCH_CLUSTER -- OFFICE_MAC : 11
SWITCH_CLUSTER --- CLUSTER_NODE_01 : 1
SWITCH_CLUSTER --- CLUSTER_NODE_02 : 2
SWITCH_CLUSTER --- CLUSTER_NODE_03 : 3
SWITCH_CLUSTER --- CLUSTER_NODE_04 : 4
SWITCH_CLUSTER --- CLUSTER_NODE_05 : 5
SWITCH_CLUSTER --- CLUSTER_NODE_06 : 6
SWITCH_CLUSTER --- CLUSTER_NODE_07 : 7
SWITCH_CLUSTER --- CLUSTER_NODE_08 : 8
SWITCH_CLUSTER -- CLUSTER_NODE_09 : 9
SWITCH_CLUSTER -- CLUSTER_NODE_10 : 10

Firewall -- SWITCH_SERVERS : uplink 

DFS ..left. NAS_TERRAMASTER: backup

CLUSTER_HOST_1 ..[hidden].. CLUSTER_NODE_01
CLUSTER_HOST_1 ..[hidden].. CLUSTER_NODE_02 
CLUSTER_HOST_2 ..[hidden].. CLUSTER_NODE_03 
CLUSTER_HOST_2 ..[hidden].. CLUSTER_NODE_04 
CLUSTER_HOST_3 ..[hidden].. CLUSTER_NODE_05
CLUSTER_HOST_3 ..[hidden].. CLUSTER_NODE_06 
CLUSTER_HOST_4 ..[hidden].. CLUSTER_NODE_07 
CLUSTER_HOST_4 ..[hidden].. CLUSTER_NODE_08
OFFICE_MNBOX_HOST .[hidden]. CLUSTER_NODE_09 
OFFICE_MNBOX_HOST .[hidden]. CLUSTER_NODE_10



@enduml

